version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    environment:
      - DB_HOST=database_ignite
      - DB_PORT=5432
    depends_on:
      - database_ignite
    links:
      - database_ignite
    volumes:
      - .:/usr/app
volumes:
  pgdata:
    driver: local
